### ISSUE TITLE
Add re-connect functionality

### ISSUE THREAD

**Issue by SuperOok** [SuperOok/openhab-vallox#2]
If connection to serial gateway is lost, the socket gets disconnected and the connection never will be established again
```
==> /var/log/openhab2/openhab.log <==
2016-11-24 09:58:20.168 [ERROR] [g.vallox.service.ValloxSerialHandler] - Failed to handle command to Vallox serial interface: java.net.SocketException: Broken pipe (Write failed)
```

The request is to implement some automatic reconnection behaviour that automatically detects disconnection and tries to reconnect.

**Comment by SuperOok** [comment]
I added some reconnection behaviour and the Thing status should now correctly represent the ONLINE/OFFLINE state. Works fine for me.

**Comment by majherek** [comment]
Thanks very much. It's works like a charm!!!
