### ISSUE TITLE
Problems with sending to vallox

### ISSUE THREAD

**Issue by SuperOok** [SuperOok/openhab-vallox#3]
Taken from #1 from @majherek:

Is this really true?
```
2016-11-24 11:15:06.196 [WARN ] [g.vallox.service.ValloxSerialHandler] - Trying to send set-command to read-only channel: PowerState Ignoring.
```
Where can I find which items/channel are read-only?

**Comment by SuperOok** [comment]
No, the error message is misleading: in that case most propably a wrong data type was sent to the PowerState channel. It only supports the OnOffType and not the DecimalType.

**Comment by SuperOok** [comment]
I enhanced the error messages a bit. 
PowerState and some other boolean properties require OnOffType commands and not DecimalType commands. If you create a "switch" item in items file and sitemap, it should work. In rules you need to use OnOffType.

See src/org.eclipse.smarthome.binding.vallox/ESH-INF/thing/thing-types.xml for details about the channels. It shows which are read-only and which are not.

**Comment by majherek** [comment]
Hi, 

thanks for explanations. In description of parameter HOST there should be RS485, not RS483 in src/org.eclipse.smarthome.binding.vallox/ESH-INF/thing/thing-types.xml.
