### ISSUE TITLE
websocket interface

### ISSUE THREAD

**Issue by mstormi** [SuperOok/openhab-vallox#5]
Hi,
any chance that you also support the websocket interface for the current Vallox MV series ?
Those units provide control through a builtin webserver. Essentially it's sending out a compact, static piece of JavaScript to get executed in the browser.
That script ultimately encodes Modbus commands and sends them over websockets to the Vallox unit, just like you currently do over RS485/TCP, so you possibly just need to implement the websocket part.
I can provide you with access to a live unit for testing if needed, and eventually with a contact at Vallox.

Not sure if it's of use, but also check out https://github.com/yozik04/vallox_websocket_api.
At least it knows all those Modbus constants...

**Comment by SuperOok** [comment]
Please note that this repository is discontinued! All development is moved to https://github.com/openhab/openhab2-addons and there at addons/binding/org.openhab.binding.vallox.

So this standalone repository is discontinued. At the moment I'm in the process of get the first version of the binding officially added to the openhab-addons. I have the first pull request here https://github.com/openhab/openhab2-addons/pull/1560

For the time being, you can obtain the bundle from the pull request from the Eclipse IOT Market Place https://marketplace.eclipse.org/content/vallox-central-venting-unit-binding

**Comment by mstormi** [comment]
using valloxmv binding now
